### PR TITLE
make matplotlib optional

### LINKED ISSUE #100: Install Matplotlib as optional extra?
Thank you for the social card previews (https://github.com/wpilibsuite/sphinxext-opengraph/pull/88), they look really good!

(I would like to generate them for the CPython docs (https://docs.python.org/), but need to check some things first, e.g. how it works with translations, how to omit them from archives/non-web builds, check our deploy process works with ~500 images and 41 MB.)

We're already using this extension for OG metadata and it's working well.

Unfortunately, the new Matplotlib dependency broke our CI yesterday because we run doctests against the CPython 3.12 development branch, and unsurprisingly the NumPy dependency isn't yet compatible (for example: [numpy.txt](https://github.com/wpilibsuite/sphinxext-opengraph/files/10701242/numpy.txt), which begins with `RuntimeWarning: NumPy 1.24.2 may not yet support Python 3.12`).

So in the meantime we have to pin to the earlier 0.7.5 release (https://github.com/python/cpython/pull/101642).

Would it be possible to have Matplotlib installable as an optional extra? Even when using Python < 3.12, it's a pretty heavy dependency to install if you don't need it.

Docs:

* https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

Thanks again!

### PR DESCRIPTION
**Pull request by TheTripleV**
closes #100

### CODE REVIEW

**Comment by Daltz333** [comment]
Will this break any existing users (aka is it opt-out instead of opt-in)?

**Comment by sciencewhiz** [comment]
Well the issue from #100 was asking for it to be opt-in, since it was added recently, right?

**Comment by TheTripleV** [comment]
If matplotlib is installed, it's opt out. If matplotlib isn't installed, it doesn't run. So it should keep existing behavior.

**Comment by Daltz333** [comment]
So this should only break CI environments for users. That still is pretty bad, but I'm not sure there is a better solution.

**Comment by TheTripleV** [comment]
No it shouldn't break ci for anyone. If matplotlib isn't installed it just turns off image generation

**Comment by Daltz333** [comment]
I wish there was a behavior where we automatically instead matplotlib and the user can explicitly choose not to instead it, instead of the opposite.

**Comment by TheTripleV** [comment]
I don't think that's possible

**Review by Daltz333 — APPROVED** [review]

**Pull request merged**
